---
# Installs basic dev tools needed for doing just about anything


- name: Install emacs
  apt: pkg=emacs24 state=installed

- name: Install emacs-live
  script: files/install-emacs-live.sh /home/{{user}} creates=/home/{{user}}/opt/emacs-live/init.el
  sudo: no
  remote_user: "{{user}}"

- name: Install nano
  apt: pkg=nano state=installed

- name: Install GIT
  apt: pkg=git update-cache=yes state=latest

- name: Install make
  apt: pkg=make state=installed

- name: Install ant
  apt: pkg=ant state=installed

- name: Install wget
  apt: pkg=wget state=installed

- name: Install tree
  apt: pkg=tree state=installed

- name: Install ag silver searcher
  apt: pkg=silversearcher-ag state=latest

- name: Install jq JSON pretty printer
  apt: pkg=jq state=installed
