---
# A playbook that installs a various dev tools
# Used for provisioning an LXC container

- hosts: all
  sudo: yes

  vars:
    tasks_dir: "tasks"

    node_version: "4.3.0"
    node_prefix: "node-v{{node_version}}"
    node_tarball: "{{node_prefix}}.tar.gz"
    node_path: "/usr/local"

  tasks:

    # Misc necessary utils like git, make etc
    - include: tasks/utils.yml user={{ansible_ssh_user}}

    # Install lang support
    - include: tasks/languages.yml

    # Install node.js
    - include: tasks/nodejs-from-src.yml

    # Install Leiningen
    - include: tasks/leiningen.yml

    # Misc configurations
    - include: tasks/misc.yml user={{ansible_ssh_user}}

    # Install nginx
    - include: tasks/nginx.yml
