---
# A playbook that installs a various dev tools
# Used for provisioning an LXC container

- hosts: all
  sudo: True
  user: username

  vars:
    tasks_dir: "tasks"

    node_version: "0.10.33"
    node_prefix: "node-v{{node_version}}"
    node_tarball: "{{node_prefix}}.tar.gz"
    node_path: "/usr/local"

  tasks:

    # Misc necessary utils like git, make etc
    - include: "tasks/utils.yml"

    # Install lang support
    - include: "tasks/languages.yml"

    # Install node.js
    - include: "tasks/nodejs-from-src.yml"

    # Install Leiningen
    - include: "tasks/leiningen.yml"
